# inspired by https://github.com/ChristopherBiscardi/advent-of-code/blob/main/2023/rust/justfile

# use `just create aoc123` to create a new contest directory
create contest:
	cargo generate --path ./template/ --name {{contest}}

# use `just test contest part` to test a part of a contest
test contest part:
	cargo nextest run -p {{contest}} {{part}}
